
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fangfun?serverTimezone=GMT%2B8
    username: root
    password: mysql314159
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml
# 日志配置
#    org.springframework.data.mongodb.core: debug
logging:
  level:
    mapper: debug
    com.example.fangfun.dao: debug


